package service

import (
	"fmt"
	"log"
	"net/smtp"

	"backend/internal/config"
	"backend/internal/model"
)

type EmailService interface {
	SendInquiryNotification(inquiry *model.Inquiry) error
}

type emailService struct {
	cfg *config.Config
}

func NewEmailService(cfg *config.Config) EmailService {
	return &emailService{cfg: cfg}
}

func (s *emailService) SendInquiryNotification(inquiry *model.Inquiry) error {
	// Craft clean HTML template body
	subject := fmt.Sprintf("Subject: [Onfix Alert] New Architecture Audit Inquiry - %s\r\n", inquiry.Name)
	mime := "MIME-version: 1.0;\r\nContent-Type: text/html; charset=\"UTF-8\";\r\n\r\n"
	
	body := fmt.Sprintf(`
		<html>
		<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; rounded: 8px;">
			<div style="background-color: #ff5e00; color: white; padding: 15px 20px; font-size: 20px; font-weight: bold; text-align: center; border-radius: 4px 4px 0 0;">
				Onfix System Intake Alert
			</div>
			<div style="padding: 20px;">
				<h3 style="color: #ff5e00; margin-top: 0;">New Architecture Audit Details</h3>
				<table style="width: 100%%; border-collapse: collapse; margin-bottom: 20px;">
					<tr>
						<td style="padding: 8px 0; font-weight: bold; width: 150px; border-bottom: 1px solid #edf2f7;">Full Name:</td>
						<td style="padding: 8px 0; border-bottom: 1px solid #edf2f7;">%s</td>
					</tr>
					<tr>
						<td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #edf2f7;">Work Email:</td>
						<td style="padding: 8px 0; border-bottom: 1px solid #edf2f7;"><a href="mailto:%s">%s</a></td>
					</tr>
					<tr>
						<td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #edf2f7;">Company:</td>
						<td style="padding: 8px 0; border-bottom: 1px solid #edf2f7;">%s</td>
					</tr>
					<tr>
						<td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #edf2f7;">Phone:</td>
						<td style="padding: 8px 0; border-bottom: 1px solid #edf2f7;">%s</td>
					</tr>
					<tr>
						<td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #edf2f7;">Core Architecture Goal:</td>
						<td style="padding: 8px 0; border-bottom: 1px solid #edf2f7; text-transform: uppercase; color: #ff5e00; font-weight: bold;">%s</td>
					</tr>
					<tr>
						<td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #edf2f7;">Date Submitted:</td>
						<td style="padding: 8px 0; border-bottom: 1px solid #edf2f7;">%s</td>
					</tr>
				</table>
				<div style="font-weight: bold; margin-bottom: 10px;">Diagnostic message & details:</div>
				<div style="background-color: #f7fafc; border-left: 4px solid #ff5e00; padding: 15px; font-style: italic; white-space: pre-wrap; font-family: monospace;">%s</div>
			</div>
			<div style="text-align: center; font-size: 11px; color: #718096; margin-top: 30px; border-top: 1px solid #edf2f7; padding-top: 15px;">
				This notification was auto-generated by the OnfixLK Go Backend.
			</div>
		</body>
		</html>
	`, inquiry.Name, inquiry.Email, inquiry.Email, inquiry.Company, inquiry.Phone, inquiry.Interest, inquiry.CreatedAt.Format("2006-01-02 15:04:05 MST"), inquiry.Message)

	msg := []byte(subject + mime + body)

	// If SMTP is not configured, fall back to console logging simulator
	if s.cfg.SMTPHost == "" || s.cfg.SMTPUser == "" {
		log.Println("------ [EMAIL SIMULATOR BEGIN] ------")
		log.Printf("SMTP host not configured. Simulating dispatch to: %s\n", s.cfg.CompanyEmail)
		log.Printf("Subject: [Onfix Alert] New Architecture Audit Inquiry - %s\n", inquiry.Name)
		log.Printf("Sender: %s\n", inquiry.Email)
		log.Printf("Interest: %s\n", inquiry.Interest)
		log.Printf("Company: %s\n", inquiry.Company)
		log.Printf("Phone: %s\n", inquiry.Phone)
		log.Printf("Message:\n%s\n", inquiry.Message)
		log.Println("------- [EMAIL SIMULATOR END] -------")
		return nil
	}

	auth := smtp.PlainAuth("", s.cfg.SMTPUser, s.cfg.SMTPPass, s.cfg.SMTPHost)
	addr := fmt.Sprintf("%s:%d", s.cfg.SMTPHost, s.cfg.SMTPPort)

	err := smtp.SendMail(addr, auth, s.cfg.SMTPUser, []string{s.cfg.CompanyEmail}, msg)
	if err != nil {
		log.Printf("Failed to send SMTP email: %v\n", err)
		return fmt.Errorf("SMTP transmission failure: %v", err)
	}

	log.Printf("HTML email alert sent successfully to %s via %s\n", s.cfg.CompanyEmail, s.cfg.SMTPHost)
	return nil
}
